name: deep_test
channels:
  - defaults
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - cudatoolkit=11.4
  - pytorch-cuda=12.1
  - pytorch=2.5.1
  - numpy==1.23.5
  - pandas==2.0.3
  - scipy==1.11.3
  - scikit-learn==1.5.1
  - yaml==0.2.5
  - zlib==1.2.13
  - seaborn==0.13.2
  - prodigal
  - tensorflow-base==2.12.0
  - tensorflow==2.12.0
  - torchaudio
  - torchvision
